/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminChatMonitor: typeof import('./src/components/admin/AdminChatMonitor.vue')['default']
    AdminUserActions: typeof import('./src/components/admin/AdminUserActions.vue')['default']
    AdminUserList: typeof import('./src/components/admin/AdminUserList.vue')['default']
    ChatHeader: typeof import('./src/components/chat/ChatHeader.vue')['default']
    ChatListItem: typeof import('./src/components/chat/ChatListItem.vue')['default']
    ChatMain: typeof import('./src/components/chat/ChatMain.vue')['default']
    ChatSidebar: typeof import('./src/components/chat/ChatSidebar.vue')['default']
    ChatSidebarFooter: typeof import('./src/components/chat/ChatSidebarFooter.vue')['default']
    ChatWindow: typeof import('./src/components/chat/ChatWindow.vue')['default']
    ConfirmDialog: typeof import('./src/components/common/ConfirmDialog.vue')['default']
    ExportDialog: typeof import('./src/components/export/ExportDialog.vue')['default']
    GroupAnnouncement: typeof import('./src/components/group/GroupAnnouncement.vue')['default']
    GroupCreateDialog: typeof import('./src/components/group/GroupCreateDialog.vue')['default']
    GroupInfo: typeof import('./src/components/group/GroupInfo.vue')['default']
    GroupInviteDialog: typeof import('./src/components/group/GroupInviteDialog.vue')['default']
    GroupList: typeof import('./src/components/group/GroupList.vue')['default']
    GroupMemberList: typeof import('./src/components/group/GroupMemberList.vue')['default']
    ImageMessage: typeof import('./src/components/chat/ImageMessage.vue')['default']
    ImagePreview: typeof import('./src/components/chat/ImagePreview.vue')['default']
    LoadingSpinner: typeof import('./src/components/common/LoadingSpinner.vue')['default']
    MessageItem: typeof import('./src/components/chat/MessageItem.vue')['default']
    MessageList: typeof import('./src/components/chat/MessageList.vue')['default']
    Modal: typeof import('./src/components/common/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('./src/components/common/Toast.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UserAvatar: typeof import('./src/components/common/UserAvatar.vue')['default']
    UserStatusDot: typeof import('./src/components/common/UserStatusDot.vue')['default']
  }
}
